export enum ActionTypes {
  CREATE_PRODUCTS = "CREATE_PRODUCTS",
  CREATE_PRODUCTS_SUCCESS = "CREATE_PRODUCTS_SUCCESS",
  CREATE_PRODUCTS_FAILURE = "CREATE_PRODUCTS_FAILURE",

  UPDATE_PRODUCTS = "UPDATE_PRODUCTS",
  UPDATE_PRODUCTS_SUCCESS = "UPDATE_PRODUCTS_SUCCESS",
  UPDATE_PRODUCTS_FAILURE = "UPDATE_PRODUCTS_FAILURE",

  DELETE_PRODUCTS = "DELETE_PRODUCTS",
  DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS",
  DELETE_PRODUCTS_FAILURE = "DELETE_PRODUCTS_FAILURE",

  GET_PRODUCTS = "GET_PRODUCTS",
  GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE",

  GET_PRODUCTS_BY_ID = "GET_PRODUCTS_BY_ID",
  GET_PRODUCTS_BY_ID_SUCCESS = "GET_PRODUCTS_BY_ID_SUCCESS",
  GET_PRODUCTS_BY_ID_FAILURE = "GET_PRODUCTS_BY_ID_FAILURE",
}
